[project]
name = "llm-debate-assistant"
version = "0.1.0"
description = "LLM powered Chinese debate assistant"
authors = [
    {name = "ianforme, whanyu1212, yatihe01, Orange-eat97"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "openai<2",
    "openai-agents==0.3.3",
    "pydantic",
    "streamlit",
    "python-dotenv",
    "ipykernel (>=6.30.1,<7.0.0)",
    "ruff (>=0.8.0,<1.0.0)",
    "docformatter (>=1.7.7,<2.0.0)",
    "pre-commit (>=4.3.0,<5.0.0)",
    "mypy (>=1.13.0,<2.0.0)",
    "detect-secrets (>=1.5.0,<2.0.0)",
    "rich (>=14.1.0,<15.0.0)",
    "litellm (<=1.77.1)",
    "pysocks",
    "websocket-client",
    "websockets",
    "opik (>=1.8.85,<2.0.0)",
    "google-genai (>=1.46.0,<2.0.0)",
    "langchain (>=1.0.2,<2.0.0)",
    "langgraph (>=1.0.1,<2.0.0)",
    "langchain-google-genai (>=3.0.0,<4.0.0)",
    "langchain-openai (>=1.0.1,<2.0.0)",
    "langchain-community (>=0.4) ; python_version >= \"3.11\" and python_version < \"3.15\"",
    "faiss-cpu (>=1.12.0,<1.13) ; python_version >= \"3.11\" and python_version < \"3.15\"",
    "livekit (>=1.0.18,<2.0.0)",
    "livekit-agents",
    "livekit-plugins-openai",
    "livekit-plugins-noise-cancellation",
    "livekit-plugins-google (>=1.2.18,<2.0.0)",
    "livekit-plugins-turn-detector (>=1.2.18,<2.0.0)",
    "livekit-plugins-silero (>=1.2.18,<2.0.0)",
    "livekit-plugins-cartesia (>=1.2.18,<2.0.0)",
    "tiktoken (>=0.12.0,<0.13.0)",
    "torch (>=2.9.1,<3.0.0) ; python_version < \"3.15\""
]

[project.optional-dependencies]
audio = [
    "pyaudio",
    "sounddevice"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
